### ISSUE TITLE
Find Alternative options for APIs

### ISSUE THREAD

**Issue by roomsiejones** [scottydphillips/sa1l#6]
In case Genius can't be used

**Comment by roomsiejones** [comment]
As a developer,
I want to have other options for Genius API,
So that if it doesn't work, the project can still be completed.

Acceptance Criteria:
When at least two other APIs that can pull lyrics or information from them are declared
Then we will have two backup APIs

**Comment by m-call** [comment]
Musixmatch is being used for the API
