### ISSUE TITLE
Search bar functionality

### ISSUE THREAD

**Issue by roomsiejones** [scottydphillips/sa1l#8]

**Comment by roomsiejones** [comment]
As a user,
I want to be able to search for songs to listen to
so that I can listen to the song I want instead of random ones

Acceptance Criteria:
When a user inputs text into the search bar and clicks search,
Then the main function runs and the text is used elsewhere

**Comment by m-call** [comment]
The functionality for the two input boxes (song and artist) as well as the search button are fully functional and display lyrics to the modal.
